spring:
  data:
    mongodb:
      uri: "your-uri"
      database: "employee_system"
      auto-index-creation: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 256MB
      max-request-size: 256MB
server:
  port: 8901